project:
  type: website
  output-dir: docs
  resources: [styles.css, theme.scss, theme-dark.scss, _quarto.yml]
lang: es
website:
  page-navigation: true
  favicon: "images/favicon.png"
  title: "TSM"
  description: "Metodología Cuantitativa y Análisis de Regresión Múltiple"
  site-url: "https://sirojasv.github.io/tsm_web"
  repo-url: https://github.com/sirojasv/tsm_web
  repo-actions: [edit, issue]
  open-graph: true
  # twitter-card:
  #   creator: ""
  #   image: "path"

  page-footer:
    # <span class="faux-block">[texto](url) | [![](path){fig-alt="descripcion" fig-align="center" width="20"}](url)[texto](url) </span>
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} 2023, Sebastián Ignacio Rojas Vergara </span> <br>
      <span class="faux-block"> [Licencia de uso Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/) </span> <br>
    right: |
      <span class="faux-block">Desarrollado con {{< fa brands r-project >}} y [Quarto](https://quarto.org) </span> <br>
      <span class="faux-block">Revisa el código fuente en {{< fa brands github >}} [GitHub](https://github.com/sirojasv/tsm_web) </span>

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sirojasv/tsm_web
        text: "Repositorio del sitio web"
      - icon: globe
        href: https://cursos.canvas.uc.cl/
        text: "Acceso a la plataforma Canvas"
      # - icon: discord
      #   href: ""
      #   text: "Dudas a través de Discord"
      - icon: envelope
        href: mailto:sirojas1@uc.cl?cc=daleal@uc.cl
        text: "Contactar por mail"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Información del curso"
        contents:
          - href: index.qmd
            text: "Descripción del curso"
          - href: course-bib.qmd
            text: "Literatura del curso"
          - href: course-team.qmd
            text: "Equipo docente"
          - href: course-contact.qmd
            text: "Atención de estudiantes"
      - section: "Material de clases {{< fa brands r-project >}}"
        contents:
          - href: header_class/header_clase_0.qmd
            text: "Clase 0"
          - href: header_class/header_clase_1.qmd
            text: "Clase 1"
      - section: "Notas {{< fa brands r-project >}}"
        contents:
          - href: notes/01_clase_1_notas/Clase_1_Notas.qmd
            text: "Notas clase 1"

format:
  html:
    theme:
      light: [pandoc, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Roboto"
    toc: true
    code-copy: true
    code-link: true
    anchor-sections: true
    code-overflow: wrap
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    smooth-scroll: true
    link-external-newwindow: true
    highlight-style: monokai
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px

# comments:
#   giscus:
#     repo: sirojasv/tsm_web
#     category: Announcements
#     mapping: pathname
#     reactions-enabled: false
#     theme: preferred_color_scheme
#     language: es

comments:
  hypothesis: true

execute:
  freeze: auto

  editor: source

editor: source
